apiVersion: v1
kind: Secret
metadata:
  name: universal-auth-credentials
  namespace: infisical-operator-system
type: Opaque
stringData:
  clientId: "26428618-6807-4a12-a461-33242ec1af50"
  clientSecret: "8176c36e0e932f660327236ad288cfb1edbbced739d9c2d074d8cedabf492ee3"
