apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - transmission-app.yaml
  - sonarr-app.yaml
  - radarr-app.yaml
  - prowlarr-app.yaml
  - overseerr-app.yaml
  - vaultwarden-app.yaml
  - homeassistant-app.yaml
  - mqtt-app.yaml
  - filebrowser-app.yaml
  - tasmoadmin-app.yaml
  - karakeep-app.yaml
  - tautulli-app.yaml
  - metrics-server-app.yaml
