apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-tunnel-controller
  labels:
    name: cloudflare-tunnel-controller
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
