---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-co-uk
  namespace: traefik
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,longhorn-system,media"
spec:
  secretName: shreck-co-uk-tls
  duration: 2160h
  renewBefore: 360h
  commonName: shreck.co.uk
  dnsNames:
    - shreck.co.uk
    - "*.shreck.co.uk"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,longhorn-system,media"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer