apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashwise
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dashwise.shreck.co.uk
      secretName: shreck-co-uk-tls
  rules:
    - host: dashwise.shreck.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashwise
                port:
                  number: 3000
