apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        fsGroup: 3000
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.51.0
        ports:
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: "Europe/London"
        - name: FILEBROWSER_CONFIG
          value: "/config/config.yaml"
        - name: FILEBROWSER_ADMIN_PASSWORD
          value: "admin"
        securityContext:
          runAsUser: 3000
          runAsGroup: 3000
        volumeMounts:
        - name: filebrowser-config-file
          mountPath: /config/config.yaml
          subPath: config.yaml
        - name: config
          mountPath: /config
        - name: database
          mountPath: /database
        - name: downloads
          mountPath: /srv/downloads
        - name: tv
          mountPath: /srv/tv
        - name: movies
          mountPath: /srv/movies
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: filebrowser-config-file
        configMap:
          name: filebrowser-config
      - name: config
        persistentVolumeClaim:
          claimName: filebrowser-config
      - name: database
        emptyDir: {}
      - name: downloads
        nfs:
          server: 10.20.0.100
          path: /mnt/Taranaki/Tarriance/hopuhopu_katoa
      - name: tv
        nfs:
          server: 10.20.0.100
          path: /mnt/Tongariro/Plexopathy/Television
      - name: movies
        nfs:
          server: 10.20.0.100
          path: /mnt/Tongariro/Plexopathy/Film
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: apps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: filebrowser
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: apps
data:
  config.yaml: |
    server:
      port: 80
      baseURL: "/"
      socket: ""
      tlsKey: ""
      tlsCert: ""
      database: "/config/database.db"
      sources:
        - path: /srv/downloads
        - path: /srv/tv
        - path: /srv/movies
    auth:
      adminUsername: "admin"
      adminPassword: "admin"
