apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: gtstef/filebrowser:stable
        ports:
        - name: http
          containerPort: 80
        env:
        - name: TZ
          value: "Europe/London"
        - name: FILEBROWSER_CONFIG
          value: "data/config.yaml"
        - name: FILEBROWSER_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: config-file
          mountPath: /home/filebrowser/data/config.yaml
          subPath: config.yaml
        - name: data
          mountPath: /home/filebrowser/data
        - name: downloads
          mountPath: /folder/downloads
        - name: tv
          mountPath: /folder/tv
        - name: movies
          mountPath: /folder/movies
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config-file
        configMap:
          name: filebrowser-config
      - name: data
        persistentVolumeClaim:
          claimName: filebrowser-data
      - name: downloads
        nfs:
          server: 10.20.0.100
          path: /mnt/Taranaki/Tarriance/hopuhopu_katoa
      - name: tv
        nfs:
          server: 10.20.0.100
          path: /mnt/Tongariro/Plexopathy/Television
      - name: movies
        nfs:
          server: 10.20.0.100
          path: /mnt/Tongariro/Plexopathy/Film
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-1
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: apps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: filebrowser
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: apps
data:
  config.yaml: |
    port: 80
    baseURL: ""
    address: ""
    log: "stdout"
    database: "data/database.db"
    root: "/folder"
