# Cloudflare API Secret
# This secret provides credentials for the tunnel controller
# Values are sourced from Infisical CLOUDFLARE_TUNNEL_API_TOKEN
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api
  namespace: cloudflare-tunnel-controller
type: Opaque
stringData:
  api-token: "xWwafGrMJMz5yssiQiD0lbzqz1UzaDVUzayycjF2"
  cloudflare-account-id: "9a7a5c367a6dd8a2e39c89f1e24db208"
  cloudflare-tunnel-name: "homelab-shreck-co-uk"
