apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudreve
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - cloudreve.shreck.co.uk
    secretName: cloudreve-tls
  rules:
  - host: cloudreve.shreck.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudreve
            port:
              number: 5212
