apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-postgres
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-1
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-redis
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-1
  resources:
    requests:
      storage: 50Gi
