apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  namespace: media
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Sonarr"
    gethomepage.dev/description: "TV series collection manager"
    gethomepage.dev/group: "Media Services"
    gethomepage.dev/icon: "sonarr.png"
    gethomepage.dev/pod-selector: "app=sonarr"
    gethomepage.dev/widget.type: "sonarr"
    gethomepage.dev/widget.url: "http://sonarr.media.svc.cluster.local:8989"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - sonarr.shreck.co.uk
      secretName: shreck-co-uk-tls
  rules:
    - host: sonarr.shreck.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989