apiVersion: v1
kind: Secret
metadata:
  name: homepage-proxmox
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
type: Opaque
stringData:
  token: "258ab66f-6460-402f-826c-72f65ac4156b"
