apiVersion: v1
kind: Secret
metadata:
  name: homepage-proxmox
  namespace: apps
  labels:
    app.kubernetes.io/name: homepage
type: Opaque
stringData:
  token: "7de26897-e5f9-4be1-b99f-7ef52e8ad879"
