apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: renovate-credentials
  namespace: platform
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: homelab-test-5-ig-k
        envSlug: prod
        secretsPath: /infrastructure
  managedSecretReference:
    secretName: renovate-credentials
    secretNamespace: platform
    secretType: Opaque
    creationPolicy: Owner
